Change version of sbt, because of error
The old version throws an error on the mac terminal:
Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"

The newer version fixed this: https://stackoverflow.com/a/44329833